version: '3.8'

services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/static:/usr/share/nginx/html/static
      - ./frontend/templates:/usr/share/nginx/html/templates
    depends_on:
      - flask
    container_name: nginx  # Убедитесь, что имя совпадает
    networks:
      - app-network

  flask:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5123:5123"
    volumes:
      - ./storage:/storage
    container_name: flask  # Убедитесь, что имя совпадает
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge